all: A/B/X/Y/target B/X/Y/target S/Z/target P/Q/target
	@echo making all

#A/B/X/Y/target: prerequisite
#	@echo MAKING $@

%/Y/target : prerequisite
	@echo making $@

%/Z/target %/Q/target : prerequisite
	@echo making $@
